package com.project.ecommerce.mapper;

import com.project.ecommerce.dto.ProductDTO;
import com.project.ecommerce.dto.ProductRequest;
import com.project.ecommerce.entity.Product;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(
        componentModel = "spring"
)
public interface ProductMapper {

    @Mapping(target = "productId", ignore = true) // Auto-generated by DB
    @Mapping(target = "user", ignore = true)      // Set manually in service layer
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Product toEntity(ProductRequest productRequest);

    @Mapping(source = "user.userId", target = "userId")
    ProductDTO toDTO(Product product);
}