spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/YOUR_DB_NAME
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  redis:
    host: YOUR_REDIS_HOST
    port: YOUR_REDIS_PORT
    password: YOUR_REDIS_PASSWORD

  cache:
    type: redis
    redis:
      time-to-live: 600000       # 10 minutes
      cache-null-values: false
      use-key-prefix: true

server:
  port: 8085
  servlet:
    context-path: /ecommerce

jwt:
  secret: "YOUR_JWT_SECRET"
  expiration-ms: 36000000       # 10 hours

logging:
  level:
    root: INFO
    com.project.ecommerce: DEBUG

payment:
  service:
    base-url: http://localhost:8081/api/v1/payments
