package com.project.ecommerce.apiresponse;

public enum ErrorCode {
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    USER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    ACCESS_DENIED,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    PRODUCT_NOT_FOUND, CART_ITEM_NOT_FOUND, CART_EMPTY
}
